### ISSUE TITLE
Error on loading "Usage Configuration"

### ISSUE THREAD

**Issue by Dinsmoor** [Kiougar/luci-wrtbwmon#19]
Hello, after upgrading to version 7, (removing version 6 all the way, then `opkg install luci-wrtbwmon7.ipk`) I am greeted by an error when navigating to the "Usage Configuration" page.

> /usr/lib/lua/luci/dispatcher.lua:433:
 >Failed to execute cbi dispatcher target for entry '/admin/network/usage_config'.
>The called action terminated with an exception:
>/usr/lib/lua/luci/cbi.lua:52: Model 'wrtbwmon' not found!
>stack traceback:
>	[C]: in function 'assert'
>	/usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
>	/usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>

The same is listed in the System Log.

I have removed /tmp/luci-modulecache and /tmp/luci-indexcache with no change.

The wrtbwmon package is installed, enabled, and started. Normal monitoring function works OK.

**Comment by Kiougar** [comment]
How did you access the `Usage Configuration` page? It shouldn't appear as a separate menu item. If that's the case then you need to have the LuCI page closed before deleting the cache files. 

From the error log I can see that the `Usage Configuration` page shouldn't be accessible as `entry '/admin/network/usage_config'`, as of version 0.7.0 it should be `/admin/network/usage/config`. Also it says that `Model 'wrtbwmon' not found!` which is true because the new model path is `wrtbwmon/config`. This means that LuCI still has the previous version of `luci-wrtbwmon` cached. 

After deleting the cache files try restarting the router if it still doesn't work.

**Comment by Dinsmoor** [comment]
@Kiougar Thanks for getting back to me quickly, I couldn't do the same because work!

Removing the cache files while not being logged onto the web page did the trick. Strange!

Thanks for the help.
